// application/web/src/views/donating/all/index.vue
<template>
  <div class="container">
    <el-alert type="success">
      <p>Account ID: {{ accountId }}</p>
      <p>Username: {{ userName }}</p>
      <p>Balance: ¥{{ balance }} CNY</p>
    </el-alert>
    <div v-if="donatingList.length === 0" style="text-align: center;">
      <el-alert title="No data found" type="warning" />
    </div>
    <el-row v-loading="loading" :gutter="20">
      <el-col v-for="(val, index) in donatingList" :key="index" :span="6" :offset="1">
        <el-card class="d-all-card">
          <div slot="header" class="clearfix">
            <span>{{ val.donatingStatus }}</span>
            <el-button
              v-if="roles[0] !== 'admin' && val.grantee === accountId && val.donatingStatus === 'In Progress'"
              style="float: right; padding: 3px 6px"
              type="text"
              @click="updateDonating(val, 'done')"
            >
              Confirm Receipt
            </el-button>
            <el-button
              v-if="roles[0] !== 'admin' && (val.donor === accountId || val.grantee === accountId) && val.donatingStatus === 'In Progress'"
              style="float: right; padding: 3px 0"
              type="text"
              @click="updateDonating(val, 'cancelled')"
            >
              Cancel
            </el-button>
          </div>
          <div class="item">
            <el-tag>Property ID: </el-tag>
            <span>{{ val.objectOfDonating }}</span>
          </div>
          <div class="item">
            <el-tag type="success">Donor ID: </el-tag>
            <span>{{ val.donor }}</span>
          </div>
          <div class="item">
            <el-tag type="danger">Recipient ID: </el-tag>
            <span>{{ val.grantee }}</span>
          </div>
          <div class="item">
            <el-tag type="warning">Created at: </el-tag>
            <span>{{ val.createTime }}</span>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import { queryDonatingList, updateDonating } from '@/api/donating';

export default {
  name: 'AllDonating',
  data() {
    return {
      loading: true,
      donatingList: [],
    };
  },
  computed: {
    ...mapGetters(['accountId', 'roles', 'userName', 'balance']),
  },
  created() {
    queryDonatingList()
      .then((response) => {
        if (response !== null) {
          this.donatingList = response;
        }
        this.loading = false;
      })
      .catch((_) => {
        this.loading = false;
      });
  },
  methods: {
    updateDonating(item, type) {
      let tip = '';
      if (type === 'done') {
        tip = 'Confirm Receipt of Donation';
      } else {
        tip = 'Cancel Donation Operation';
      }
      this.$confirm('Do you want to ' + tip + '?', 'Prompt', {
        confirmButtonText: 'OK',
        cancelButtonText: 'Cancel',
        type: 'success',
      })
        .then(() => {
          this.loading = true;
          updateDonating({
            donor: item.donor,
            grantee: item.grantee,
            objectOfDonating: item.objectOfDonating,
            status: type,
          })
            .then((response) => {
              this.loading = false;
              if (response !== null) {
                this.$message({
                  type: 'success',
                  message: tip + ' Succeeded!',
                });
              } else {
                this.$message({
                  type: 'error',
                  message: tip + ' Failed!',
                });
              }
              setTimeout(() => {
                window.location.reload();
              }, 1000);
            })
            .catch((_) => {
              this.loading = false;
            });
        })
        .catch(() => {
          this.loading = false;
          this.$message({
            type: 'info',
            message: tip + ' Canceled',
          });
        });
    },
  },
};
</script>

<style>
.container {
  width: 100%;
  text-align: center;
  min-height: 100%;
  overflow: hidden;
}

.tag {
  float: left;
}

.item {
  font-size: 14px;
  margin-bottom: 18px;
  color: #999;
}

.clearfix:before,
.clearfix:after {
  display: table;
}
.clearfix:after {
  clear: both;
}

.d-all-card {
  width: 280px;
  height: 300px;
  margin: 18px;
}
</style>

// application/client/src/views/donating/all/index.jsx
import React, { useState, useEffect } from 'react';

function AllDonating() {
  const [loading, setLoading] = useState(true);
  const [donatingList, setDonatingList] = useState([]);
  const [confirmType, setConfirmType] = useState('');
  const [selectedDonation, setSelectedDonation] = useState(null);

  const accountId = 'Your Account ID'; // Replace with your actual account ID
  const roles = ['Your Role']; // Replace with your actual role
  const userName = 'Your Username'; // Replace with your actual username
  const balance = 'Your Balance'; // Replace with your actual balance

  const queryDonatingList = () => {
    // Simulate the API call for querying donating list
    // Replace this with your actual API call
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve([]);
      }, 1000);
    });
  };

  const updateDonating = (item, type) => {
    // Simulate the API call for updating donating
    // Replace this with your actual API call
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({});
      }, 1000);
    });
  };

  useEffect(() => {
    queryDonatingList()
      .then((response) => {
        if (response !== null) {
          setDonatingList(response);
        }
        setLoading(false);
      })
      .catch((_) => {
        setLoading(false);
      });
  }, []);

  const handleUpdateDonating = (item, type) => {
    let tip = '';
    if (type === 'done') {
      tip = 'Confirm Receipt of Donation';
    } else {
      tip = 'Cancel Donation Operation';
    }

    if (window.confirm(`Do you want to ${tip}?`)) {
      setLoading(true);
      updateDonating({
        donor: item.donor,
        grantee: item.grantee,
        objectOfDonating: item.objectOfDonating,
        status: type,
      })
        .then((response) => {
          setLoading(false);
          if (response !== null) {
            alert(`${tip} Succeeded!`);
          } else {
            alert(`${tip} Failed!`);
          }
          setTimeout(() => {
            window.location.reload();
          }, 1000);
        })
        .catch((_) => {
          setLoading(false);
        });
    } else {
      alert(`${tip} Canceled`);
    }
  };

  return (
    <div className="container">
      <div className="el-alert" style={{ backgroundColor: 'lightgreen' }}>
        <p>Account ID: {accountId}</p>
        <p>Username: {userName}</p>
        <p>Balance: ¥{balance} CNY</p>
      </div>
      {donatingList.length === 0 ? (
        <div style={{ textAlign: 'center' }}>
          <div className="el-alert" style={{ backgroundColor: 'lightcoral' }}>
            No data found
          </div>
        </div>
      ) : (
        <div className="el-row" style={{ gutter: 20 }}>
          {donatingList.map((val, index) => (
            <div key={index} style={{ span: 6, offset: 1 }}>
              <div className="el-card d-all-card">
                <div className="clearfix">
                  <span>{val.donatingStatus}</span>
                  {roles[0] !== 'admin' &&
                    val.grantee === accountId &&
                    val.donatingStatus === 'In Progress' && (
                      <button
                        style={{
                          float: 'right',
                          padding: '3px 6px',
                          background: 'none',
                          border: 'none',
                          textDecoration: 'underline',
                        }}
                        onClick={() => handleUpdateDonating(val, 'done')}
                      >
                        Confirm Receipt
                      </button>
                    )}
                  {roles[0] !== 'admin' &&
                    (val.donor === accountId || val.grantee === accountId) &&
                    val.donatingStatus === 'In Progress' && (
                      <button
                        style={{
                          float: 'right',
                          padding: '3px 0',
                          background: 'none',
                          border: 'none',
                          textDecoration: 'underline',
                        }}
                        onClick={() => handleUpdateDonating(val, 'cancelled')}
                      >
                        Cancel
                      </button>
                    )}
                </div>
                <div className="item">
                  <span>Property ID: {val.objectOfDonating}</span>
                </div>
                <div className="item">
                  <span>Donor ID: {val.donor}</span>
                </div>
                <div className="item">
                  <span>Recipient ID: {val.grantee}</span>
                </div>
                <div className="item">
                  <span>Created at: {val.createTime}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default AllDonating;
