// application/client/src/views/login/index.jsx
import React, { useState, useEffect } from 'react';
import { queryAccountList } from '../../api/account';
import { useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';

function Login() {
  const [loading, setLoading] = useState(false);
  const [redirect, setRedirect] = useState(undefined);
  const [accountList, setAccountList] = useState([]);
  const [value, setValue] = useState('');
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const handleLogin = () => {
    if (value) {
      setLoading(true);
      // Simulate the login action
      // Replace this with your actual login logic
      setTimeout(() => {
        setLoading(false);
        // Dispatch user data to Redux store
        dispatch({
          type: 'SET_ACCOUNT',
          payload: {
            accountId: value, // Assuming value is the selected user's accountId
            userName: 'User Name', // Replace with actual user name
            roles: ['user'], // Replace with actual user roles
          },
        });
        // Redirect after login
        // Replace this with your actual redirect logic
        navigate('/realestate'); // Redirect to the default path or your desired path
      }, 2000);
    } else {
      alert('Please select a user role'); // Replace this with your actual notification method
    }
  }

  const selectGet = (e) => {
    setValue(e.target.value);
  };

  useEffect(() => {
    // Load account list on component mount
    queryAccountList()
      .then((response) => {
        if (response !== null) {
          setAccountList(response);
        }
      });
  }, []);

  return (
    <div className="login-container">
      <div className="login-form" autoComplete="on">
        <div className="title-container">
          <h3 className="title">Real Estate Transaction System Based on Blockchain</h3>
        </div>
        <select value={value} onChange={selectGet} className="login-select">
          <option value="" disabled>Select user role</option>
          {accountList.map((item) => (
            <option key={item.accountId} value={item.accountId}>
              {item.userName} - {item.accountId}
            </option>
          ))}
        </select>
        <button
          className="el-button"
          style={{ width: '100%', marginBottom: '30px' }}
          onClick={handleLogin}
          disabled={loading}
        >
          {loading ? 'Loading...' : 'Enter'}
        </button>
        <div className="tips">
          <span>Tips: Choose different user roles to simulate transactions</span>
        </div>
      </div>
    </div>
  );
}

export default Login;

// application/web/src/views/login/index.vue
<template>
  <div class="login-container">
    <el-form ref="loginForm" class="login-form" auto-complete="on" label-position="left">

      <div class="title-container">
        <h3 class="title">Real Estate Transaction System Based on Blockchain</h3>
      </div>
      <el-select v-model="value" placeholder="Select user role" class="login-select" @change="selectGet">
        <el-option
          v-for="item in accountList"
          :key="item.accountId"
          :label="item.userName"
          :value="item.accountId"
        >
          <span style="float: left">{{ item.userName }}</span>
          <span style="float: right; color: #8492a6; font-size: 13px">{{ item.accountId }}</span>
        </el-option>
      </el-select>

      <el-button :loading="loading" type="primary" style="width:100%;margin-bottom:30px;" @click.native.prevent="handleLogin">Enter</el-button>

      <div class="tips">
        <span style="margin-right:20px;">Tips: Choose different user roles to simulate transactions</span>
      </div>

    </el-form>
  </div>
</template>

<script>
import { queryAccountList } from '@/api/account'

export default {
  name: 'Login',
  data() {
    return {
      loading: false,
      redirect: undefined,
      accountList: [],
      value: ''
    }
  },
  watch: {
    $route: {
      handler: function(route) {
        this.redirect = route.query && route.query.redirect
      },
      immediate: true
    }
  },
  created() {
    queryAccountList().then(response => {
      if (response !== null) {
        this.accountList = response
      }
    })
  },
  methods: {
    handleLogin() {
      if (this.value) {
        this.loading = true
        this.$store.dispatch('account/login', this.value).then(() => {
          this.$router.push({ path: this.redirect || '/' })
          this.loading = false
        }).catch(() => {
          this.loading = false
        })
      } else {
        this.$message('Please select a user role')
      }
    },
    selectGet(accountId) {
      this.value = accountId
    }
  }
}
</script>

<style lang="scss" scoped>
$bg: #2d3a4b;
$dark_gray: #889aa4;
$light_gray: #eee;

.login-container {
  min-height: 100%;
  width: 100%;
  background-color: $bg;
  overflow: hidden;

  .login-form {
    position: relative;
    width: 520px;
    max-width: 100%;
    padding: 160px 35px 0;
    margin: 0 auto;
    overflow: hidden;
  }
  .login-select{
   padding: 20px 0px 30px 0px;
   min-height: 100%;
   width: 100%;
   background-color: $bg;
   overflow: hidden;
   text-align: center;
  }
  .tips {
    font-size: 14px;
    color: #fff;
    margin-bottom: 10px;

    span {
      &:first-of-type {
        margin-right: 16px;
      }
    }
  }

  .svg-container {
    padding: 6px 5px 6px 15px;
    color: $dark_gray;
    vertical-align: middle;
    width: 30px;
    display: inline-block;
  }

  .title-container {
    position: relative;

    .title {
      font-size: 26px;
      color: $light_gray;
      margin: 0px auto 40px auto;
      text-align: center;
      font-weight: bold;
    }
  }

  .show-pwd {
    position: absolute;
    right: 10px;
    top: 7px;
    font-size: 16px;
    color: $dark_gray;
    cursor: pointer;
    user-select: none;
  }
}
</style>
