// application/client/src/views/realestate/add/index.jsx
import React, { useState, useEffect } from 'react';

function AddRealEstate() {
  const [loading, setLoading] = useState(false);
  const [accountList, setAccountList] = useState([]);
  const [ruleForm, setRuleForm] = useState({
    proprietor: '',
    totalArea: 0,
    livingSpace: 0,
  });

  const checkArea = (value) => {
    return value > 0 ? '' : 'Must be greater than 0';
  };

  const submitForm = (e) => {
    e.preventDefault();
    setLoading(true);

    // Simulate the createRealEstate API call
    // Replace this with your actual API call
    setTimeout(() => {
      setLoading(false);
      // Simulate a successful response
      // Replace this with actual API response handling
      const response = true;

      if (response) {
        alert('Creation successful!'); // Replace with your preferred notification method
      } else {
        alert('Creation failed!'); // Replace with your preferred notification method
      }
    }, 2000);
  };

  const resetForm = () => {
    setRuleForm({
      proprietor: '',
      totalArea: 0,
      livingSpace: 0,
    });
  };

  const selectGet = (e) => {
    setRuleForm({
      ...ruleForm,
      proprietor: e.target.value,
    });
  };

  useEffect(() => {
    // Load account list on component mount
    // Simulate the queryAccountList API call
    // Replace this with your actual API call
    const queryAccountList = () => {
      return new Promise((resolve) => {
        setTimeout(() => {
          // Simulate a response with accountList data
          // Replace this with actual API response data
          const accountList = [
            { accountId: 1, userName: 'User1' },
            { accountId: 2, userName: 'User2' },
            // Add more account data as needed
          ];
          resolve(accountList);
        }, 1000);
      });
    };

    queryAccountList().then((response) => {
      if (response !== null) {
        // Filter out the admin user
        const filteredAccountList = response.filter(
          (item) => item.userName !== 'Admin'
        );
        setAccountList(filteredAccountList);
      }
    });
  }, []);

  return (
    <div className="app-container">
      <form className="el-form" onSubmit={submitForm}>
        <div className="el-form-item">
          <label className="el-form-item__label">Owner</label>
          <select
            value={ruleForm.proprietor}
            onChange={selectGet}
            className="el-select"
          >
            <option value="" disabled>
              Select Owner
            </option>
            {accountList.map((item) => (
              <option key={item.accountId} value={item.accountId}>
                {item.userName} - {item.accountId}
              </option>
            ))}
          </select>
        </div>
        <div className="el-form-item">
          <label className="el-form-item__label">Total Area (㎡)</label>
          <input
            type="number"
            value={ruleForm.totalArea}
            onChange={(e) => {
              setRuleForm({ ...ruleForm, totalArea: e.target.value });
            }}
            step="0.1"
            min="0"
          />
        </div>
        <div className="el-form-item">
          <label className="el-form-item__label">Living Space (㎡)</label>
          <input
            type="number"
            value={ruleForm.livingSpace}
            onChange={(e) => {
              setRuleForm({ ...ruleForm, livingSpace: e.target.value });
            }}
            step="0.1"
            min="0"
          />
        </div>
        <div className="el-form-item">
          <button type="submit" className="el-button" disabled={loading}>
            {loading ? 'Loading...' : 'Create Now'}
          </button>
          <button
            type="button"
            className="el-button"
            onClick={resetForm}
          >
            Reset
          </button>
        </div>
      </form>
    </div>
  );
}

export default AddRealEstate;

// application/web/src/views/realestate/add/index.vue
<template>
  <div class="app-container">
    <el-form ref="ruleForm" v-loading="loading" :model="ruleForm" :rules="rules" label-width="100px">

      <el-form-item label="Owner" prop="proprietor">
        <el-select v-model="ruleForm.proprietor" placeholder="Select Owner" @change="selectGet">
          <el-option
            v-for="item in accountList"
            :key="item.accountId"
            :label="item.userName"
            :value="item.accountId"
          >
            <span style="float: left">{{ item.userName }}</span>
            <span style="float: right; color: #8492a6; font-size: 13px">{{ item.accountId }}</span>
          </el-option>
        </el-select>
      </el-form-item>
      <el-form-item label="Total Area (㎡)" prop="totalArea">
        <el-input-number v-model="ruleForm.totalArea" :precision="2" :step="0.1" :min="0" />
      </el-form-item>
      <el-form-item label="Living Space (㎡)" prop="livingSpace">
        <el-input-number v-model="ruleForm.livingSpace" :precision="2" :step="0.1" :min="0" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('ruleForm')">Create Now</el-button>
        <el-button @click="resetForm('ruleForm')">Reset</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import { queryAccountList } from '@/api/account';
import { createRealEstate } from '@/api/realEstate';

export default {
  name: 'AddRealEstate',
  data() {
    var checkArea = (rule, value, callback) => {
      if (value <= 0) {
        callback(new Error('Must be greater than 0'));
      } else {
        callback();
      }
    };
    return {
      ruleForm: {
        proprietor: '',
        totalArea: 0,
        livingSpace: 0,
      },
      accountList: [],
      rules: {
        proprietor: [
          { required: true, message: 'Select an owner', trigger: 'change' },
        ],
        totalArea: [
          { validator: checkArea, trigger: 'blur' },
        ],
        livingSpace: [
          { validator: checkArea, trigger: 'blur' },
        ],
      },
      loading: false,
    };
  },
  computed: {
    ...mapGetters(['accountId']),
  },
  created() {
    queryAccountList().then(response => {
      if (response !== null) {
        // Filter out the admin user
        this.accountList = response.filter(item =>
          item.userName !== 'Admin'
        );
      }
    });
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          this.$confirm('Create now?', 'Confirmation', {
            confirmButtonText: 'OK',
            cancelButtonText: 'Cancel',
            type: 'success',
          }).then(() => {
            this.loading = true;
            createRealEstate({
              accountId: this.accountId,
              proprietor: this.ruleForm.proprietor,
              totalArea: this.ruleForm.totalArea,
              livingSpace: this.ruleForm.livingSpace,
            }).then(response => {
              this.loading = false;
              if (response !== null) {
                this.$message({
                  type: 'success',
                  message: 'Creation successful!',
                });
              } else {
                this.$message({
                  type: 'error',
                  message: 'Creation failed!',
                });
              }
            }).catch(_ => {
              this.loading = false;
            });
          }).catch(() => {
            this.loading = false;
            this.$message({
              type: 'info',
              message: 'Creation canceled',
            });
          });
        } else {
          return false;
        }
      });
    },
    resetForm(formName) {
      this.$refs[formName].resetFields();
    },
    selectGet(accountId) {
      this.ruleForm.proprietor = accountId;
    },
  },
};
</script>

<style scoped>
</style>
